# Generated by Django 5.2.4 on 2025-09-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('validade', models.DateField()),
                ('estoque', models.IntegerField()),
            ],
        ),
    ]
