# Generated by Django 5.2.6 on 2025-09-25 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emprestimo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='criado_em',
            new_name='data_emprestimo',
        ),
        migrations.RenameField(
            model_name='emprestimo',
            old_name='devolvido',
            new_name='status',
        ),
    ]
