# Generated by Django 5.2.4 on 2025-09-27 12:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_criado_em_emprestimo_data_emprestimo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='condicao_equipamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_prevista_devolucao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
