# Generated by Django 5.2.4 on 2025-09-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_emprestimo_observacao_alter_emprestimo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='atualizado_em',
        ),
    ]
